# .spec-kit/config.yaml
name: Phase-2
version: "1.0"
 
structure:
  specs_dir: specs
  features_dir: specs/003-full-stack-todo-app/features
  api_dir: specs/003-full-stack-todo-app/api
  database_dir: specs/003-full-stack-todo-app/database
  ui_dir: specs/003-full-stack-todo-app/ui


phases:
  - name: phase1-console
    features: [task-crud]
  - name: phase2-web
    features: [task-crud, authentication]
  - name: phase3-chatbot
    features: [task-crud, authentication, chatbot]

